### ISSUE TITLE
Linux Installation Issue

### ISSUE THREAD

**Issue by arcsector** [gen0cide/gscript#100]
When I try `$ go get github.com/gen0cide/gscript/cmd/gscript` the system returns:
```
# github.com/gen0cide/gscript/compiler/computil
go/src/github.com/gen0cide/gscript/compiler/computil/packages.go:48:21: undefined: gopkgs.Packages
```
Here's my `PATH` and Go version:
```
$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/george/.local/bin:/home/george/bin:/usr/local/go/bin
$ go version
go version go1.11 linux/amd64
```

Also, in the installation readme, please change `cd ~/go/src/github.com/gen0cide/cmd/gscript` to `cd ~/go/src/github.com/gen0cide/gscript/cmd/gscript`

**Comment by ahhh** [comment]
Hey @arcsector I think I fixed the issue. I also changed those lines in the installation guide.
Thanks for the feedback! Let me know if it works now.

**Comment by arcsector** [comment]
Works on CentOS release 7.5.1804 (Core). Closing. Thanks again!
